name: type-check

on:
  push:
    paths:
      - '*.py'
  pull_request:

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install pgn-dwnloader and dev dependencies
        run: pip install ".[dev]"
      - name: Run mypy
        run: mypy
